### ISSUE TITLE
Reconcile capitalisation of crime severity score weight table and generated event files 

### ISSUE THREAD

**Issue by danbirks** [Sparrow0hawk/crime_sim_toolkit#26]
Currently the capitalisation of the matched crime severity score procedure crime_des_CSSweights.csv (column Offence_Description) does not match the capitalisation in the synthetic events generated by the sampler/historic data. 

In particular Offence_Description in the above file is all lowercase - and inconsistently capitalised in the event files.

Can these be reconciled? - likely the most sensible option is for both files to use all lower-case. This should be easily accomplished by just changing the case in the event generator.

**Comment by Sparrow0hawk** [comment]
Example of output from [CrimeDes_to_CSS.ipynb](https://github.com/Sparrow0hawk/crime_sim_toolkit/blob/master/data_manipulation/CrimeDes_toCSS.ipynb).

Note Offence_Description column is lowercase (as specified for string matching).

  | Policeuk_Cat | Offence_Group | Offence_Subgroup | Offence_Description | Offence_code | Weight
-- | -- | -- | -- | -- | -- | --
Violence and Sexual Offences | Violence against the person | Homicide | homicide | 1/4.1/4.10/4.2 | 7973.393423
Violence and Sexual Offences | Violence against the person | Violence without injury | assault without injury on a constable | 104 | 15.087613
Violence and Sexual Offences | Violence against the person | Violence without injury | assault without injury | 105A | 27.021083

**Comment by Sparrow0hawk** [comment]
Key to note this is an issue not of this package but an issue for the output into the ABM (model of supply)

**Comment by Sparrow0hawk** [comment]
Closing this issue inline with merge #33
